"""initial schema - OpFlow reorder tables (exact DDL from opflow_spec.md)

Revision ID: 0001
Revises:
Create Date: 2026-08-13

This migration renders the DDL from opflow_spec.md (Schema v1) byte-for-byte
via op.execute. It is intentionally NOT autogenerated, so the committed SQL
is the single source of truth and can be hand-diffed against the spec.
"""
import textwrap

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _run(statements: list[str]) -> None:
    """Execute a list of raw DDL/DML statements, one op.execute each.

    PSYCOPG does not reliably batch multiple statements in a single
    execute call, so each statement is issued on its own.
    """
    for statement in statements:
        op.execute(textwrap.dedent(statement).strip())


def upgrade() -> None:
    statements = [
        # --- vendors ---
        """
        CREATE TABLE vendors (
            id              SERIAL PRIMARY KEY,
            name            TEXT NOT NULL,
            contact_email   TEXT NOT NULL,
            lead_time_days  INTEGER NOT NULL DEFAULT 7,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        # --- inventory_items ---
        """
        CREATE TABLE inventory_items (
            id                SERIAL PRIMARY KEY,
            sku               TEXT NOT NULL UNIQUE,
            name              TEXT NOT NULL,
            quantity_on_hand  INTEGER NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
            reorder_threshold INTEGER NOT NULL,
            reorder_quantity  INTEGER NOT NULL,
            vendor_id         INTEGER NOT NULL REFERENCES vendors(id),
            updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        """
        CREATE INDEX idx_inventory_vendor ON inventory_items(vendor_id);
        """,
        """
        CREATE INDEX idx_inventory_reorder_check ON inventory_items(quantity_on_hand, reorder_threshold);
        """,
        # --- process_types ---
        """
        CREATE TABLE process_types (
            id                     SERIAL PRIMARY KEY,
            name                   TEXT NOT NULL UNIQUE,
            description            TEXT,
            poll_interval_seconds  INTEGER NOT NULL DEFAULT 60,
            allowed_tools          JSONB NOT NULL,
            max_attempts           INTEGER NOT NULL DEFAULT 3,
            enabled                BOOLEAN NOT NULL DEFAULT true,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        # --- jobs ---
        """
        CREATE TABLE jobs (
            id               SERIAL PRIMARY KEY,
            process_type_id  INTEGER NOT NULL REFERENCES process_types(id),
            idempotency_key  TEXT NOT NULL UNIQUE,
            inventory_item_id INTEGER REFERENCES inventory_items(id),
            status           TEXT NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending','running','succeeded','failed','retrying')),
            attempts         INTEGER NOT NULL DEFAULT 0,
            next_run_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            payload          JSONB,
            error            TEXT,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        """
        CREATE INDEX idx_jobs_poll ON jobs(status, next_run_at);
        """,
        # --- purchase_orders ---
        """
        CREATE TABLE purchase_orders (
            id                  SERIAL PRIMARY KEY,
            vendor_id           INTEGER NOT NULL REFERENCES vendors(id),
            inventory_item_id   INTEGER NOT NULL REFERENCES inventory_items(id),
            quantity            INTEGER NOT NULL CHECK (quantity > 0),
            status              TEXT NOT NULL DEFAULT 'draft'
                                  CHECK (status IN ('draft','sent','confirmed')),
            created_by_job_id   INTEGER REFERENCES jobs(id),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        # --- audit_log ---
        """
        CREATE TABLE audit_log (
            id                 SERIAL PRIMARY KEY,
            job_id             INTEGER NOT NULL REFERENCES jobs(id),
            tool_called        TEXT NOT NULL,
            tool_input         JSONB,
            tool_output        JSONB,
            decision_reasoning TEXT,
            timestamp          TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """,
        """
        CREATE INDEX idx_audit_job ON audit_log(job_id);
        """,
        # --- seed: low_stock_reorder process type ---
        """
        INSERT INTO process_types (name, description, poll_interval_seconds, allowed_tools, max_attempts)
        VALUES (
            'low_stock_reorder',
            'When an item drops below its reorder threshold, draft a PO and notify the vendor.',
            60,
            '["query_inventory","create_purchase_order","notify_vendor"]'::jsonb,
            3
        );
        """,
    ]
    _run(statements)

def downgrade() -> None:
    # Reverse the upgrade: drop indexes, then tables, in dependency order.
    statements = [
        """DROP INDEX IF EXISTS idx_audit_job;""",
        """DROP INDEX IF EXISTS idx_jobs_poll;""",
        """DROP INDEX IF EXISTS idx_inventory_reorder_check;""",
        """DROP INDEX IF EXISTS idx_inventory_vendor;""",
        """DROP TABLE IF EXISTS audit_log;""",
        """DROP TABLE IF EXISTS purchase_orders;""",
        """DROP TABLE IF EXISTS jobs;""",
        """DROP TABLE IF EXISTS process_types;""",
        """DROP TABLE IF EXISTS inventory_items;""",
        """DROP TABLE IF EXISTS vendors;""",
    ]
    _run(statements)