"""jobs.idempotency_key immutable after insert (trigger)

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-14

Enforces the poller's uniqueness guarantee at the DATABASE level, not just
in application code: idempotency_key is the deterministic dedup key the
poller recomputes per (process_type, item, day), and enqueue_job relies on
the UNIQUE constraint + ON CONFLICT DO NOTHING. If anyone ever mutates an
existing row's idempotency_key directly (a tampering probe, a buggy tool,
manual SQL), the poller recomputes the original key, finds it free, and
enqueues a DUPLICATE job. This trigger closes that hole: idempotency_key is
immutable after insert.

Hand-authored (not autogenerated), same convention as 0001: the committed
DDL is the single source of truth.
"""
import textwrap

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def _run(statements: list[str]) -> None:
    """Execute a list of raw DDL/DML statements, one op.execute each.

    PSYCOPG does not reliably batch multiple statements in a single
    execute call, so each statement is issued on its own.
    """
    for statement in statements:
        op.execute(textwrap.dedent(statement).strip())


def upgrade() -> None:
    statements = [
        # Trigger function: raises unconditionally when the trigger fires.
        """\
        CREATE OR REPLACE FUNCTION jobs_idempotency_key_immutable()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'jobs.idempotency_key is immutable after insert';
        END;
        $$ LANGUAGE plpgsql;
        """,
        # BEFORE UPDATE + WHEN clause: only fire when the key actually changes.
        """\
        CREATE TRIGGER jobs_idempotency_key_immutable
        BEFORE UPDATE ON jobs
        FOR EACH ROW
        WHEN (NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key)
        EXECUTE FUNCTION jobs_idempotency_key_immutable();
        """,
    ]
    _run(statements)


def downgrade() -> None:
    statements = [
        """\
        DROP TRIGGER IF EXISTS jobs_idempotency_key_immutable ON jobs;
        """,
        """\
        DROP FUNCTION IF EXISTS jobs_idempotency_key_immutable();
        """,
    ]
    _run(statements)
